# Generated by Django 4.0.4 on 2022-04-27 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='설문지 제목')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='설문지 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 날짜')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_title', models.CharField(max_length=100, verbose_name='질문')),
                ('item1', models.CharField(max_length=100, verbose_name='옵션')),
                ('item2', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션')),
                ('item3', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션')),
                ('item4', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션')),
                ('item5', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션')),
                ('item6', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_q.question')),
            ],
        ),
    ]
