# Generated by Django 4.0.4 on 2022-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_q', '0002_choice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='category',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio'), ('select', 'select')], default='checkbox', max_length=10, verbose_name='유형 선택'),
        ),
    ]
