# Generated by Django 4.0.4 on 2022-04-27 01:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey_q', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='작성자 전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_q.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='설문 질문 응답')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_q.choice', verbose_name='설문 질문 항목')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_a.participant', verbose_name='설문 작성자')),
            ],
        ),
    ]
